---
title: Ann's Fancy Faces
phone: 01234567890
email: booking@annfancyface.co.uk
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  testimonials:
    title: Testimonials
    output: true
  uploads:
    title: Uploads
    output: true
