---
title: The Mad Hatter
phone: '07756145046'
email: ann.themadhatter@gmail.com
timezone: GMT+1

include: ["_pages"]
collections:
  posts:
    title: Posts
    output: true
  testimonials:
    title: Testimonials
    output: true
  uploads:
    title: Uploads
    output: true
